/** Common U.S. ticker → Chinese reference names (shown when available). */
export const CHINESE_NAMES: Record<string, string> = {
  AAPL: "苹果",
  MSFT: "微软",
  NVDA: "英伟达",
  GOOGL: "谷歌",
  GOOG: "谷歌",
  AMZN: "亚马逊",
  META: "Meta",
  TSLA: "特斯拉",
  AVGO: "博通",
  "BRK.A": "伯克希尔",
  "BRK.B": "伯克希尔",
  JPM: "摩根大通",
  V: "维萨",
  MA: "万事达",
  UNH: "联合健康",
  XOM: "埃克森美孚",
  JNJ: "强生",
  WMT: "沃尔玛",
  PG: "宝洁",
  LLY: "礼来",
  COST: "好市多",
  NFLX: "奈飞",
  AMD: "超威半导体",
  HD: "家得宝",
  BAC: "美国银行",
  ORCL: "甲骨文",
  CRM: "赛富时",
  KO: "可口可乐",
  PEP: "百事",
  MRK: "默克",
  ABBV: "艾伯维",
  CVX: "雪佛龙",
  TMO: "赛默飞",
  CSCO: "思科",
  ACN: "埃森哲",
  MCD: "麦当劳",
  ABT: "雅培",
  WFC: "富国银行",
  LIN: "林德",
  DHR: "丹纳赫",
  TXN: "德州仪器",
  INTC: "英特尔",
  QCOM: "高通",
  AMAT: "应用材料",
  INTU: "财捷",
  AMGN: "安进",
  ISRG: "直觉外科",
  BX: "黑石",
  CAT: "卡特彼勒",
  GE: "通用电气",
  IBM: "IBM",
  GS: "高盛",
  MS: "摩根士丹利",
  BA: "波音",
  RTX: "雷神",
  HON: "霍尼韦尔",
  UPS: "联合包裹",
  NEE: "新纪元能源",
  PM: "菲利普莫里斯",
  DIS: "迪士尼",
  BKNG: "缤客",
  ADP: "自动数据处理",
  SPGI: "标普全球",
  BLK: "贝莱德",
  NOW: "ServiceNow",
  UBER: "优步",
  PLTR: "帕兰提尔",
  SHOP: "Shopify",
  SBUX: "星巴克",
  T: "美国电话电报",
  VZ: "威瑞森",
  CMCSA: "康卡斯特",
  PFE: "辉瑞",
  BMY: "百时美施贵宝",
  MDT: "美敦力",
  GILD: "吉利德",
  LOW: "劳氏",
  TJX: "TJX",
  NKE: "耐克",
  DE: "迪尔",
  LMT: "洛克希德马丁",
  UNP: "联合太平洋",
  SCHW: "嘉信理财",
  C: "花旗",
  AXP: "美国运通",
  PYPL: "贝宝",
  COF: "第一资本",
  MU: "美光",
  LRCX: "拉姆研究",
  KLAC: "科磊",
  ADI: "亚德诺",
  PANW: "派拓网络",
  CRWD: "CrowdStrike",
  SNOW: "Snowflake",
  ABNB: "爱彼迎",
  CMG: "奇波雷",
  MAR: "万豪",
  F: "福特",
  GM: "通用汽车",
  CVS: "西维斯健康",
  MO: "奥驰亚",
  SO: "南方电力",
  BABA: "阿里巴巴",
  JD: "京东",
  PDD: "拼多多",
  BIDU: "百度",
  NIO: "蔚来",
  XPEV: "小鹏汽车",
  LI: "理想汽车",
  TSM: "台积电",
  ASML: "阿斯麦",
  ARM: "安谋",
  SMCI: "超微电脑",
  COIN: "Coinbase",
  MRNA: "Moderna",
  REGN: "再生元",
  VRTX: "福泰制药",
  SNPS: "新思科技",
  CDNS: "铿腾电子",
  ADSK: "欧特克",
  TEAM: "Atlassian",
  DELL: "戴尔",
  HPE: "慧与",
  HPQ: "惠普",
  DOW: "陶氏化学",
  FDX: "联邦快递",
  TMUS: "T-Mobile",
  CHTR: "特许通讯",
  ELV: "联合健康集团",
  CI: "信诺",
  HUM: "哈门那",
  BSX: "波士顿科学",
  SYK: "史赛克",
  ZTS: "硕腾",
  CL: "高露洁",
  KMB: "金佰利",
  CLX: "高乐氏",
  GIS: "通用磨坊",
  KHC: "卡夫亨氏",
  MDLZ: "亿滋",
  STZ: "星座品牌",
  TAP: "摩森康胜",
  DUK: "杜克能源",
  AEP: "美国电力",
  EXC: "爱克斯龙",
  SRE: "森科能源",
  D: "道明尼能源",
  PLD: "Prologis",
  AMT: "美国电塔",
  EQIX: "Equinix",
  SPY: "标普500 ETF",
  QQQ: "纳斯达克100 ETF",
};

function shortEnglishName(name: string, max = 22): string {
  const clean = name.replace(/\s+Common Stock.*$/i, "").replace(/\s+Inc\.?$/i, "").trim();
  if (clean.length <= max) return clean;
  return `${clean.slice(0, max - 1)}…`;
}

export function chineseStockName(symbol: string): string | undefined {
  const key = symbol.trim().toUpperCase();
  return CHINESE_NAMES[key];
}

/** Prefer Chinese name; fall back to shortened English. Pass merged cache on the client when available. */
export function displayStockName(
  symbol: string,
  englishName?: string,
  mergedCache?: Record<string, string>,
): string {
  const key = symbol.trim().toUpperCase();
  return mergedCache?.[key] ?? CHINESE_NAMES[key] ?? shortEnglishName(englishName?.trim() || symbol);
}
