export type ListedCompany = {
  symbol: string;
  name: string;
  sector: string;
};

/** Liquid U.S. large/mid-cap equity universe used for buy-list scans. */
export const UNIVERSE: ListedCompany[] = [
  { symbol: "AAPL", name: "Apple", sector: "Tech" },
  { symbol: "MSFT", name: "Microsoft", sector: "Tech" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Semiconductors" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Tech" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer" },
  { symbol: "META", name: "Meta", sector: "Tech" },
  { symbol: "TSLA", name: "Tesla", sector: "Auto" },
  { symbol: "AVGO", name: "Broadcom", sector: "Semiconductors" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Finance" },
  { symbol: "JPM", name: "JPMorgan", sector: "Finance" },
  { symbol: "V", name: "Visa", sector: "Finance" },
  { symbol: "MA", name: "Mastercard", sector: "Finance" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Health" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health" },
  { symbol: "WMT", name: "Walmart", sector: "Retail" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Staples" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Health" },
  { symbol: "COST", name: "Costco", sector: "Retail" },
  { symbol: "NFLX", name: "Netflix", sector: "Media" },
  { symbol: "AMD", name: "AMD", sector: "Semiconductors" },
  { symbol: "HD", name: "Home Depot", sector: "Retail" },
  { symbol: "BAC", name: "Bank of America", sector: "Finance" },
  { symbol: "ORCL", name: "Oracle", sector: "Tech" },
  { symbol: "CRM", name: "Salesforce", sector: "Tech" },
  { symbol: "KO", name: "Coca-Cola", sector: "Staples" },
  { symbol: "PEP", name: "PepsiCo", sector: "Staples" },
  { symbol: "MRK", name: "Merck", sector: "Health" },
  { symbol: "ABBV", name: "AbbVie", sector: "Health" },
  { symbol: "CVX", name: "Chevron", sector: "Energy" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Health" },
  { symbol: "CSCO", name: "Cisco", sector: "Tech" },
  { symbol: "ACN", name: "Accenture", sector: "Tech" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer" },
  { symbol: "ABT", name: "Abbott", sector: "Health" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Finance" },
  { symbol: "LIN", name: "Linde", sector: "Materials" },
  { symbol: "DHR", name: "Danaher", sector: "Health" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Semiconductors" },
  { symbol: "INTC", name: "Intel", sector: "Semiconductors" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Semiconductors" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Semiconductors" },
  { symbol: "INTU", name: "Intuit", sector: "Tech" },
  { symbol: "AMGN", name: "Amgen", sector: "Health" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health" },
  { symbol: "BX", name: "Blackstone", sector: "Finance" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
  { symbol: "IBM", name: "IBM", sector: "Tech" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Finance" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Finance" },
  { symbol: "BA", name: "Boeing", sector: "Industrials" },
  { symbol: "RTX", name: "RTX", sector: "Industrials" },
  { symbol: "HON", name: "Honeywell", sector: "Industrials" },
  { symbol: "UPS", name: "UPS", sector: "Industrials" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "PM", name: "Philip Morris", sector: "Staples" },
  { symbol: "DIS", name: "Disney", sector: "Media" },
  { symbol: "BKNG", name: "Booking", sector: "Consumer" },
  { symbol: "ADP", name: "ADP", sector: "Tech" },
  { symbol: "SPGI", name: "S&P Global", sector: "Finance" },
  { symbol: "BLK", name: "BlackRock", sector: "Finance" },
  { symbol: "NOW", name: "ServiceNow", sector: "Tech" },
  { symbol: "UBER", name: "Uber", sector: "Consumer" },
  { symbol: "PLTR", name: "Palantir", sector: "Tech" },
  { symbol: "SHOP", name: "Shopify", sector: "Tech" },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer" },
  { symbol: "T", name: "AT&T", sector: "Telecom" },
  { symbol: "VZ", name: "Verizon", sector: "Telecom" },
  { symbol: "CMCSA", name: "Comcast", sector: "Media" },
  { symbol: "PFE", name: "Pfizer", sector: "Health" },
  { symbol: "BMY", name: "Bristol Myers", sector: "Health" },
  { symbol: "MDT", name: "Medtronic", sector: "Health" },
  { symbol: "GILD", name: "Gilead", sector: "Health" },
  { symbol: "LOW", name: "Lowe's", sector: "Retail" },
  { symbol: "TJX", name: "TJX", sector: "Retail" },
  { symbol: "NKE", name: "Nike", sector: "Consumer" },
  { symbol: "DE", name: "John Deere", sector: "Industrials" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Finance" },
  { symbol: "C", name: "Citigroup", sector: "Finance" },
  { symbol: "AXP", name: "American Express", sector: "Finance" },
  { symbol: "PYPL", name: "PayPal", sector: "Finance" },
  { symbol: "COF", name: "Capital One", sector: "Finance" },
  { symbol: "MU", name: "Micron", sector: "Semiconductors" },
  { symbol: "LRCX", name: "Lam Research", sector: "Semiconductors" },
  { symbol: "KLAC", name: "KLA", sector: "Semiconductors" },
  { symbol: "ADI", name: "Analog Devices", sector: "Semiconductors" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Tech" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Tech" },
  { symbol: "SNOW", name: "Snowflake", sector: "Tech" },
  { symbol: "ABNB", name: "Airbnb", sector: "Consumer" },
  { symbol: "CMG", name: "Chipotle", sector: "Consumer" },
  { symbol: "MAR", name: "Marriott", sector: "Consumer" },
  { symbol: "F", name: "Ford", sector: "Auto" },
  { symbol: "GM", name: "General Motors", sector: "Auto" },
  { symbol: "CVS", name: "CVS Health", sector: "Health" },
  { symbol: "MO", name: "Altria", sector: "Staples" },
  { symbol: "SO", name: "Southern Co", sector: "Utilities" },
];

export const DEFAULT_SYMBOLS = ["AAPL", "NVDA", "MSFT"];

export function companyName(symbol: string): string {
  return UNIVERSE.find((c) => c.symbol === symbol.toUpperCase())?.name ?? symbol.toUpperCase();
}

export function universeSymbols(): string[] {
  return UNIVERSE.map((c) => c.symbol);
}
